name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make
      
    - name: Run
      run: make run
      
    - name: Clean
      run: make clean
